#!/usr/bin/env python3
# PYTHON_ARGCOMPLETE_OK

import re
import sys

from ace_metrics.cli import cli_metrics

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(cli_metrics())
